package pojos;
// Generated 6 Oct, 2018 2:41:50 PM by Hibernate Tools 3.6.0



/**
 * Employees generated by hbm2java
 */
public class Employees  implements java.io.Serializable {


     private Integer id;
     private Address address;
     private String FName;
     private String LName;

    public Employees() {
    }

    public Employees(Address address, String FName, String LName) {
       this.address = address;
       this.FName = FName;
       this.LName = LName;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Address getAddress() {
        return this.address;
    }
    
    public void setAddress(Address address) {
        this.address = address;
    }
    public String getFName() {
        return this.FName;
    }
    
    public void setFName(String FName) {
        this.FName = FName;
    }
    public String getLName() {
        return this.LName;
    }
    
    public void setLName(String LName) {
        this.LName = LName;
    }




}


